"""fg department

Revision ID: 151686646c19
Revises: 46779b1b370d
Create Date: 2025-12-03 11:14:47.198033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151686646c19'
down_revision = '46779b1b370d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gaji_setting', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'departemen', ['departemen_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gaji_setting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
