"""gaji setting

Revision ID: 46779b1b370d
Revises: 99a90fd9ccd4
Create Date: 2025-12-02 10:42:40.044186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46779b1b370d'
down_revision = '99a90fd9ccd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gaji_setting',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('departemen_id', sa.String(length=255), nullable=False),
    sa.Column('jabatan_id', sa.String(length=255), nullable=False),
    sa.Column('status_kerja_id', sa.String(length=255), nullable=False),
    sa.Column('gaji_pokok', sa.Integer(), nullable=False),
    sa.Column('tunjangan_pokok', sa.Integer(), nullable=False),
    sa.Column('total_tunjangan_opsional', sa.Integer(), nullable=True),
    sa.Column('total_potongan_opsional', sa.Integer(), nullable=True),
    sa.Column('total_gaji', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jabatan_id'], ['jabatan_karyawan.id'], ),
    sa.ForeignKeyConstraint(['status_kerja_id'], ['status_kerja_karyawan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gaji_setting_potongan',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('gaji_setting_id', sa.String(length=255), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gaji_setting_id'], ['gaji_setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gaji_setting_tunjangan',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('gaji_setting_id', sa.String(length=255), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gaji_setting_id'], ['gaji_setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gaji_setting_tunjangan')
    op.drop_table('gaji_setting_potongan')
    op.drop_table('gaji_setting')
    # ### end Alembic commands ###
