"""penambahan table kunjungan

Revision ID: 48d146ed6684
Revises: 
Create Date: 2025-12-25 01:48:18.053492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d146ed6684'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kunjungan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_karyawan', sa.String(length=255), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kunjungan_foto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_kunjungan', sa.Integer(), nullable=False),
    sa.Column('foto', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('jam', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_kunjungan'], ['kunjungan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kunjungan_foto')
    op.drop_table('kunjungan')
    # ### end Alembic commands ###
