"""init

Revision ID: 6c20cbd78a35
Revises: 
Create Date: 2025-11-30 05:53:14.690192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c20cbd78a35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gaji_rule',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('id_jabatan_karyawan', sa.String(length=255), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_jabatan_karyawan'], ['jabatan_karyawan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gaji_rule')
    # ### end Alembic commands ###
