"""penambahan kondisi tanggal update dan create

Revision ID: 833942d469ef
Revises: fdb76ea80a92
Create Date: 2025-12-17 15:40:22.072780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833942d469ef'
down_revision = 'fdb76ea80a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
