"""departemen

Revision ID: 99a90fd9ccd4
Revises: 
Create Date: 2025-12-02 10:34:33.694365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a90fd9ccd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departemen',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('nama_departemen', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_departemen', sa.String(length=255), nullable=False))
        batch_op.create_foreign_key(None, 'departemen', ['id_departemen'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_departemen')

    op.drop_table('departemen')
    # ### end Alembic commands ###
