"""penambahan table transaksi absen

Revision ID: c7ea43e8ff49
Revises: acf352078ff2
Create Date: 2025-12-23 00:35:04.334904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ea43e8ff49'
down_revision = 'acf352078ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('transaksi_absensi',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('id_karyawan', sa.String(length=255), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jam_in', sa.Time(), nullable=True),
    sa.Column('jam_out', sa.Time(), nullable=True),
    sa.Column('foto_in', sa.String(length=255), nullable=True),
    sa.Column('foto_out', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_karyawan'], ['karyawan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi_absensi')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
