"""longitude dan latitude absen

Revision ID: e5e4bbbb5006
Revises: 48d146ed6684
Create Date: 2025-12-27 23:54:04.336814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e4bbbb5006'
down_revision = '48d146ed6684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunjungan', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'karyawan', ['id_karyawan'], ['id'])

    with op.batch_alter_table('transaksi_absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude_in', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('latitude_in', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude_out', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('latitude_out', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi_absensi', schema=None) as batch_op:
        batch_op.drop_column('latitude_out')
        batch_op.drop_column('longitude_out')
        batch_op.drop_column('latitude_in')
        batch_op.drop_column('longitude_in')

    with op.batch_alter_table('kunjungan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
