"""init

Revision ID: 07aa4d22f404
Revises: 
Create Date: 2025-11-30 04:55:06.053671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07aa4d22f404'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('karyawan',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('id_status_pernikahan', sa.String(length=255), nullable=False),
    sa.Column('id_jabatan_karyawan', sa.String(length=255), nullable=False),
    sa.Column('id_kondisi_akun', sa.String(length=255), nullable=False),
    sa.Column('id_agama', sa.String(length=255), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=False),
    sa.Column('npwp', sa.String(length=50), nullable=True),
    sa.Column('status_pajak', sa.String(length=50), nullable=True),
    sa.Column('durasi_kontrak', sa.Integer(), nullable=True),
    sa.Column('no_hp', sa.Integer(), nullable=False),
    sa.Column('tanggal_masuk', sa.String(length=255), nullable=False),
    sa.Column('awal_kontrak', sa.Date(), nullable=False),
    sa.Column('akhir_kontrak', sa.Date(), nullable=False),
    sa.Column('id_status_kerja_karyawan', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_agama'], ['agama.id'], ),
    sa.ForeignKeyConstraint(['id_jabatan_karyawan'], ['jabatan_karyawan.id'], ),
    sa.ForeignKeyConstraint(['id_kondisi_akun'], ['kondisi_akun.id'], ),
    sa.ForeignKeyConstraint(['id_status_kerja_karyawan'], ['status_kerja_karyawan.id'], ),
    sa.ForeignKeyConstraint(['id_status_pernikahan'], ['status_pernikahan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik')
    )
    with op.batch_alter_table('agama', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_agama', sa.String(length=255), nullable=False))
        batch_op.drop_column('agama')

    with op.batch_alter_table('kondisi_akun', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_kondisi_akun', sa.String(length=255), nullable=False))
        batch_op.drop_column('kondisi_akun')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kondisi_akun', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kondisi_akun', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('nama_kondisi_akun')

    with op.batch_alter_table('agama', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agama', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('nama_agama')

    op.drop_table('karyawan')
    # ### end Alembic commands ###
