"""fix nik to string

Revision ID: 88875be08252
Revises: 8d91846a5fb9
Create Date: 2025-11-17 19:23:06.204102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88875be08252'
down_revision = '8d91846a5fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.alter_column('nik',
               existing_type=mysql.INTEGER(display_width=16),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.alter_column('nik',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(display_width=16),
               existing_nullable=False)

    # ### end Alembic commands ###
