"""add durasi_kontrak

Revision ID: 8d91846a5fb9
Revises: 22ee0341b7aa
Create Date: 2025-11-17 18:47:34.995744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d91846a5fb9'
down_revision = '22ee0341b7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('npwp', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status_pajak', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('durasi_kontrak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.drop_column('durasi_kontrak')
        batch_op.drop_column('status_pajak')
        batch_op.drop_column('npwp')

    # ### end Alembic commands ###
